### ISSUE TITLE
Manager not working past Elixir 1.12.x?

### ISSUE THREAD

**Issue by jasonbarbee** [antonmi/ALF#5]
Interesting library, I'm looking forward to working with it, but ran into some errors launching the Manager process.
I had this problem with my production repo, but confirmed I can replicate it with a fresh mix new example:

mix new myalf --sup  myalf
add deps -       {:alf, "~> 0.7"}
add a file copy and paste the example "ThePipeline" from the ALF repo Readme page.
if mix.exs defines elixir 1.12.x and you launch with 1.12.x it works fine.
If I bump the mix.exs elixir version and launch the same working repo instead with Elixir 1.13.x or 1.14.x - I cannot start the ALF.Manager - get a traceback, and with / without sync enabled doesn't matter.

```
iex(1)> :ok = ALF.Manager.start(ThePipeline, sync: true)
07:15:18.590 [error] GenServer ThePipeline terminating
** (FunctionClauseError) no function clause matching in ALF.Manager.terminate/2
    (alf 0.7.0) lib/manager.ex:149: ALF.Manager.terminate({{:case_clause, {{:function, :add_one, 2}, 10, ["add_one(event, opts)"], :none, %{}}}, [{ALF.SourceCode, :function_doc, 2, [file: 'lib/source_code.ex', line: 24]}, {ALF.Components.Stage, :read_source_code, 2, [file: 'lib/components/stage.ex', line: 2]}, {ALF.Components.Stage, :init_sync, 2, [file: 'lib/components/stage.ex', line: 43]}, {ALF.Builder, :"-do_build_sync/3-fun-3-", 3, [file: 'lib/builder.ex', line: 86]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 2396]}, {ALF.Builder, :build_sync, 2, [file: 'lib/builder.ex', line: 44]}, {ALF.Manager, :handle_continue, 2, [file: 'lib/manager.ex', line: 165]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 689]}]}, %ALF.Manager{autoscaling_enabled: false, components: [], name: ThePipeline, pid: #PID<0.617.0>, pipeline: nil, pipeline_module: ThePipeline, pipeline_sup_pid: nil, producer_pid: nil, registry: %{}, registry_dump: %{}, stages_to_be_deleted: [], sup_pid: #PID<0.606.0>, sync: true, telemetry_enabled: false})
    (stdlib 3.14) gen_server.erl:727: :gen_server.try_terminate/3
    (stdlib 3.14) gen_server.erl:912: :gen_server.terminate/10
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :init_pipeline}
State: %ALF.Manager{autoscaling_enabled: false, components: [], name: ThePipeline, pid: #PID<0.617.0>, pipeline: nil, pipeline_module: ThePipeline, pipeline_sup_pid: nil, producer_pid: nil, registry: %{}, registry_dump: %{}, stages_to_be_deleted: [], sup_pid: #PID<0.606.0>, sync: true, telemetry_enabled: false} 
```

Wondering if you have seen this or can confirm?

I'm on MacOS 12.6 / Monterey. 
Elixir 1.12 + OTP 22 - good.
1.13.1, 1.13.4, and 1.14.0 + OTP 23 all resulted in this crash.

Thanks!

**Comment by antonmi** [comment]
Hey-hey @jasonbarbee !
Let me check

**Comment by antonmi** [comment]
Yeah, I can reproduce it!
Thank you for the issue!
I'll fix that soon and let you know

**Comment by antonmi** [comment]
Hey @jasonbarbee !
The issue was caused by a slightly different behavior of Code.fetch_docs in Elixir 1.13 (and 1.14).
Please use version 0.7.1.
I set Elixir version to 1.13, so it won't work with 1.12 anymore. Please use 1.13 or 1.14
