### ISSUE TITLE
How to send an event to another Pipeline

### ISSUE THREAD

**Issue by fermuch** [antonmi/ALF#9]
This might be a dumb question, since it is already possible to solve by using a **stage**, but, is there an ALF-way to send an event from one pipeline to another?

As an example:

**DecoderPipeline** receives a raw message and converts it to a `Message`. Extracts metadata and saves it in the database. Based on the "kind" of message, it should then be routed to another pipeline.

The other pipelines handle logic specific to that kind of event.

As far as I understand, the only way right now to do this is to call/cast the pipeline from a stage.

**Comment by antonmi** [comment]
Hey @fermuch !
Calling another pipeline from a stage is a possible solution, however, it may lead to a quite complex topology.
And it's also hard to visualize the flow in ALFMonitor.

If the "event" in the original pipeline is similar to the one in another pipeline, I would rather combine the pipelines in one big pipeline and use "switch" to send events to the corresponding branches.

If the "event" is quite different. You can implement your own "middleware/adapter" logic, that first sends an event to the original pipeline, then takes the result, prepares a new event, and sends it to another pipeline.
